### ISSUE TITLE
bug: not getting plugins inside lua directory in config dir.

### ISSUE THREAD

**Issue by kiyoon** [folke/neodev.nvim#106]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Ubuntu 22.04

### Describe the bug

I tried to search the relevant issue but I couldn't find a solution yet.  
It works in the plugin dirs, and the root of the config dir.   
However, if I go inside `~/.config/nvim/lua/user` it suddenly stops working.  
It will only work with something like `require("user.options").` but it doesn't work with plugins `require("mason").`  

![image](https://user-images.githubusercontent.com/12980409/212213330-8dae4d6f-1112-4de7-9e8d-fc4ffc9c4dfd.png)

### Steps To Reproduce

1. Go to  `~/.config/nvim/lua/user` 
2. Open `nvim lsp.lua`
3. Try `require("lspconfig")` and it won't show suggestions.

### Expected Behavior

Load plugins within config directory's lua folder

**Comment by folke** [comment]
I can't reproduce this.

What does `LspInfo` show as your root dir?

And what is the output of `:lua= vim.fn.stdpath("config")`.

Is your .config folder a symlink? Anything else special about your system? Using Nix or something like that?

**Comment by kiyoon** [comment]
1. Yes, it is a symlink.
2. `/home/kiyoon/bin/vimrc4ubuntu/lua`
![image](https://user-images.githubusercontent.com/12980409/212317825-455e3a9e-0eb5-409a-81c2-c187956d6ac1.png)

If I go to the root config dir, it changes to `/home/kiyoon/bin/vimrc4ubuntu` and it works.

3. `:lua= vim.fn.stdpath("config")` -> "/home/kiyoon/.config/nvim"
4. I'm using Ubuntu 22.04. I lately switched to lazy.nvim and removed CoC. I still had neodev but I don't know if it did anything beforehand. I didn't notice the problem before.

**Comment by milanglacier** [comment]
I can confirm the issue. I don't use symlinks.

```lua
 Client: sumneko_lua (id: 1, bufnr: [10, 21])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/me/.config/nvim
 	cmd:             lua-language-server
```

and `:lua= vim.fn.stdpath("config")` gives ` /Users/me/.config/nvim`

Indeed, when typing `require('xxxx')`, it gives me completions like `lua.conf.xxx`, instead of `conf.xxx`.

I am assuming that the runtime path appending when setting up lua-language-server is broken?

**Comment by folke** [comment]
@kiyoon are you using a lua-language-server version >= 3.6.0?

**Comment by folke** [comment]
@milanglacier that has nothing to do with op's issue.
Are you using lua-language-server >= 3.6.0?

**Comment by milanglacier** [comment]
> @milanglacier that has nothing to do with op's issue.
> Are you using lua-language-server >= 3.6.0?

Yes, it is 3.6.4.

I change the runtime path to the following line and it works as before:

```
                runtime = {
                    path = { 'lua/?.lua', 'init.lua' },
                    pathStrict = true,
                },

```

**Comment by folke** [comment]
@milanglacier I just pushed an update. Can you see if that works?

The changes you are proposing are incorrect btw.

**Comment by folke** [comment]
@kiyoon your problem is most likely because you are using an outdated version os sumneko that doesnt have my fixes for `pathStrict` and workspace folders

**Comment by milanglacier** [comment]
> @milanglacier I just pushed an update. Can you see if that works?
> 
> The changes you are proposing are incorrect btw.

Yes it works.

I am thinking about if it actually caused by the obsolete `.luarc.json` automatically created (when asked by the popup prompt to do so) at the era before 3.6...

I removed this file and the settings worked as expected now.

**Comment by folke** [comment]
That file would indeed give different rootdirs, but Neodev handles those situations. Rootdirs for sumneko are wrong for a lot of users due to mis-configuration.

Instead of always needing to tell the user they need to fix their ldpconfig setup, I just fix it inside Neodev.

**Comment by milanglacier** [comment]
> That file would indeed give different rootdirs, but Neodev handles those situations. Rootdirs for sumneko are wrong for a lot of users due to mis-configuration.
> 
> Instead of always needing to tell the user they need to fix their ldpconfig setup, I just fix it inside Neodev.

Yes it now works like a charm and much more smoother! Thanks for your work!

**Comment by kiyoon** [comment]
I installed the latest neodev and it didn't work. I have lua-language-server 3.6.4.

The problem was `.luarc.json` and after removing it it works well. Thanks!

**Comment by folke** [comment]
Having that file in a directory probbaly would return a scoped config to sumneko, and as such ignoring the neodev config
