### ISSUE TITLE
bug: override not working

### ISSUE THREAD

**Issue by zegervdv** [folke/neodev.nvim#108]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Ubuntu 22.04

### Describe the bug

I'm using chezmoi to manage my dotfiles, and as such my init.lua is not in the default location.
I use the `override` option to setup to enable neodev in the chezmoi folder:
``` require('neodev').setup {
  override = function(root_dir, options)
    vim.pretty_print('ROOT: ' .. root_dir)
    if require('neodev.util').has_file(root_dir, os.getenv('HOME') .. '/.local/share/chezmoi') then
      options.enabled = true
      options.runtime = true
      options.types = true
      options.plugins = true
    end
  end,
}
```

Since a34a9e7e775f1513466940c31285292b7b8375de that function does not seem to be working anymore (or even called?)
The debug print I have in there is no longer showing up in the messages.

### Steps To Reproduce

1. Have non-default location of init.lua
2. set the override option

### Expected Behavior

Have the override option (or something equivalent) work again :)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/neodev.nvim",
  -- add any other plugins here
  'neovim/nvim-lspconfig',
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

require('neodev').setup {
  override = function (root_dir, options)
    print('hello')
  end
}

require('lspconfig').sumneko_lua.setup {}
```

**Comment by folke** [comment]
That `has_file` was an internal function, but I removed that since it's no longer used.

change it to `if rootdir:find("chezmoi") then` or something similar

**Comment by zegervdv** [comment]
I don't think it is calling the override function anymore. In the repro.lua I've added a print which is no longer showing up since that commit.

**Comment by folke** [comment]
Closing again. It does work for me.
Use `vim.notify("hello")` to see the message

**Comment by zegervdv** [comment]
Okay, must be something with my machine then. Even in a docker container the notify doesn't show up.

**Comment by folke** [comment]
The notify will only come up when lspconfig is configured

**Comment by zegervdv** [comment]
I added some prints and found out that in lsp.lua `lua_root` is nil, which causes `#lua_root` to error silently.
When changing `... and #lua_root` to `... and lua_root and #lua_root` it does continue to calling the override function.
Now just need to figure out why `lua_root` is nil on my setup.

**Comment by folke** [comment]
Fixed!

**Comment by zegervdv** [comment]
Thanks!

**Comment by folke** [comment]
correct. just updated the readme
