### ISSUE TITLE
feature: use lua-language-server's builtin luv meta library

### ISSUE THREAD

**Issue by T-727** [folke/neodev.nvim#127]
### Did you check the docs?

- [X] I have read all the neodev.nvim docs

### Is your feature request related to a problem? Please describe.

Hey!
So I've noticed that [`luv`](https://github.com/LuaLS/lua-language-server/tree/master/meta/3rd/luv) has been added to `lua-language-server`'s [builtin meta libraries](https://github.com/LuaLS/lua-language-server/wiki/Libraries#built-in-libraries) since 3 months ago..
And so it would be nice to simply replace the `luv` metadata from neodev with `lua-language-server`'s and have much more complete `luv` information :)

### Describe the solution you'd like

- Add `"${3rd}/luv/library"` to `workspace.library`
- Annotate `vim.loop` with `@type` `uv`

### Describe alternatives you've considered

Stay as is.

### Additional context

According to this test:
https://github.com/neovim/neovim/tree/master/test/functional/lua/loop_spec.lua#L154
`vim.loop` isn't modified from `luv` so there shouldn't be any clashes.

#### Potential caveat
If a user updates their `lua-language-server` version but not Neovim, there could be a slight desync in information.

**Comment by folke** [comment]
Awesome, didn't know that!

Just updated the code. Types will be re-generated in a bit
