### ISSUE TITLE
bug: Required modules are not resolved correctly on multiple workspaces

### ISSUE THREAD

**Issue by musjj** [folke/neodev.nvim#133]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-987+g371a74e4e

### Operating system/version

Windows 10

### Describe the bug

Required modules are not resolved correctly after the second opened project and onwards. This bug does not occur when neodev isn't activated.

### Steps To Reproduce

1. Open a lua project
2. Open a second lua project from a different root
3. Hover over a required module

### Expected Behavior

Modules should resolve and auto-complete correctly.

### Repro

```Lua
local root = vim.loop.os_tmpdir() .. "/nvim-repro"
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath }
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
  "folke/tokyonight.nvim",
  "folke/neodev.nvim",
  {
    "neovim/nvim-lspconfig",
    event = { "BufReadPost", "BufNewFile" },
    keys = { { "K", vim.lsp.buf.hover } },
    config = function()
      vim.lsp.set_log_level("debug")
      require("neodev").setup()
      require("lspconfig").lua_ls.setup {
        settings = { Lua = { workspace = { checkThirdParty = false } } },
      }
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by folke** [comment]
This is not a nneodev bug. This is due to a change in lspconfig a couple of months ago. No idea how to fix it. Check there

**Comment by musjj** [comment]
The issue does not happen without neodev though.
Note that this issue is different from the currently ongoing issue with diagnostic errors.
With just lspconfig, you will get diagnostic errors, but modules will still be required correctly. You can check the minimal config.
