### ISSUE TITLE
bug: config dir indexing yields different results upon opening different config files

### ISSUE THREAD

**Issue by haoming-li-ling** [folke/neodev.nvim#147]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS 13.2.1

### Describe the bug

I have lua files under both `lua/` and `luasnippets/` (for LuaSnip snippets written in lua) in my nvim config directory. If I open a lua file in the `.config/nvim/lua/` directory first, then the entirety of the config directory is indexed. However, if I open a file from `.config/nvim/luasnippets/` directory first, then none of the files in `.config/nvim` are indexed, only those from the plugins are.

### Steps To Reproduce

1. Open a lua file in `.config/nvim/luasnippets/` 
2. Try to `gd` in this file into a required module stored in `.config/nvim/lua`, nothing happens, the jump fails
3. Yet `gd` works in the same file on required modules of installed plugins

### Expected Behavior

Whatever lua file is opend inside `.config/nvim/`, the entirety of `.config/nvim/` should be indexed.

**Comment by folke** [comment]
That's not a bug. That's your lsp setup that detects a different root dir.
Fix your root dir or use the config.override option.

**Comment by haoming-li-ling** [comment]
But in both cases the root dir is the same, the whole `.config/nvim` folder is treated as the root.

**Comment by haoming-li-ling** [comment]
There is a directory names `lua/` in the `luasnippets/` folder, which contains snippets for the lua filetype. Neodev seems to believe that `luasnippets/` is a plugin dir. However, even if I override the settings for `luansippets/`, setting every `library` option to true, the modules in `.config/nvim/` are still not indexed if I open any file in `luasnippets/` first.
