### ISSUE TITLE
bug: sign_place() can't accept buffer name as "buf" param

### ISSUE THREAD

**Issue by kyoh86** [folke/neodev.nvim#156]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-d31f764

### Operating system/version

Windows 11

### Describe the bug

If we call sign_place() with buffer name like below:
```
              vim.fn.sign_place(100, "", "cursor", vim.fn.expand("%:p"), { lnum = vim.fn.line(".") })
```

diagnosis reports warning like below:

```
Cannot assign `string` to parameter `integer`.
 - `string` cannot match `integer`
 - Type `string` cannot match `integer`
```

But sign_place should accept buffer name according to help.

> `sign_place({id}, {group}, {name}, {buf} [, {dict}])`
> ...
> 		`{buf}` refers to a buffer name or number. For the accepted
> 		values, see `bufname()`.

### Steps To Reproduce

1. call sign_place with buffer-name.
2. diagnosis.
3. you will get the warning

### Expected Behavior

no warning

### Repro

```Lua
Sorry for that now I have no time to prepare it.
I should do it later if you need.
```

**Comment by wookayin** [comment]
buf is not string. The nightly-generated `vim.fn` annotation is correct as it specifies `any` type. https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_meta/vimfn.lua

**Comment by kyoh86** [comment]
This issue is too old and no longer needs to be addressed.
As usual, I don't understand the difference between issues that are reacted to and those that are not.
