### ISSUE TITLE
feature: Possibly generate luacheckrc or selene configs of the neovim API?

### ISSUE THREAD

**Issue by nogweii** [folke/neodev.nvim#171]
### Did you check the docs?

- [X] I have read all the neodev.nvim docs

### Is your feature request related to a problem? Please describe.

I'd like to use a CLI linter like [luacheck](https://github.com/mpeterv/luacheck) or [selene](https://github.com/Kampfkarren/selene) but with the correct knowledge of Neovim's APIs.

### Describe the solution you'd like

A generated file that can be referenced/included in the configuration for these tools that has all of the functions spelled out.

### Describe alternatives you've considered

Configure the tools to not care deeply about the `vim` global. This works just fine today, but it'd be neat.

### Additional context

To configure luacheck, you'd need to create a file that contains all of the globals and their fields, and mark which ones are read-only and not. [Details on the syntax is in their documentation.](https://luacheck.readthedocs.io/en/stable/config.html)

To configure selene, they have migrated to [a YAML-based format](https://kampfkarren.github.io/selene/usage/std.html) to describe an API. This seems to include support for types, which provides an overlapping / more through feature.

**Comment by wookayin** [comment]
I believe this has nothing to do with neodev.nvim at all. Should you need any linter/formatting tool, you should install them separately outside neovim.

**Comment by nogweii** [comment]
> Should you need any linter/formatting tool, you should install them separately outside neovim.

Oh, I'm not advocating for neodev to install them automatically. However, a bunch of work has been done to add a lot of types for the neovim api, can that work be reused to generate the configuration file(s) for these linters?

**Comment by wookayin** [comment]
Sorry, I don't think I get what you are meaning. Would you mind describing more clearly? What are those "work" and "these linters"? 

If you need a rc file for stylua or other linters, you will need to configure them separately for your project. Like copy-paste from https://github.com/neovim/neovim/blob/master/.luacheckrc; what does neovim have to do with what you want to achieve here?
