### ISSUE TITLE
bug: example .neoconf.json uses "sumneko_lua" instead of "lua_ls"

### ISSUE THREAD

**Issue by sp3ctum** [folke/neodev.nvim#177]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2086+g965dbd0e0

### Operating system/version

macOS 14.2.1 (23C71)

### Describe the bug

The documentation indicates an example for configuring the lua language server.
![image](https://github.com/folke/neodev.nvim/assets/300791/f6990897-ddd1-4150-a7c7-39d2db63ce01)

I am learning nvim plugin development and my head is spinning a bit, so I may be clueless.
But it seems like sumneko_lua has been deprecated and lua_ls should be used instead:
- https://www.reddit.com/r/neovim/comments/1107xiz/how_to_fix_sumneko_lua_is_deprecated_use_lua_ls/
- https://github.com/neovim/nvim-lspconfig/pull/2439

### Steps To Reproduce

1. Open the file in this project, for example
2. Start adding a new setting for the language server, for example `"Lua.hint.enable`"
3. Nothing shows up.

---

Was expecting this (it works if you change it to `lua_ls`, which I have done here):
<img width="951" alt="image" src="https://github.com/folke/neodev.nvim/assets/300791/65ed24bf-e300-4c82-9fb2-50f340d502b4">

### Expected Behavior

Completions and documentation should be visible for the available settings.

**Comment by wookayin** [comment]
Duplicate of #174

**Comment by sp3ctum** [comment]
I think you are correct; this is a duplicate of #174.
Closing.
