### ISSUE TITLE
bug: no completions in `~/.config/nvim/after` directory

### ISSUE THREAD

**Issue by Danielkonge** [folke/neodev.nvim#179]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1e0996b57

### Operating system/version

macOS 14.2.1

### Describe the bug

I updated my plugins via `Lazy` today, and `neodev` doesn't seem to work in my `after` directory anymore, but it does still work in `~/.config/nvim/lua/myname`. (It also doesn't work in the directory with my local versions of plugins.)

Completions and type information worked until I updated and I assume something with the paths changed? (I don't know if this is related to #178?)

When I tell Lazy to use commit `3941036e3da9b0dc09244036d20c590b6d752175`, everything works as expected.

### Steps To Reproduce

Try to get completions or type details for `vim.<anything>` in the `after` directory. 

If you can't replicate this, I can try to make more detailed reproduction steps, but I assume it is an issue with the paths in general.

My `neodev` setup is just:
```lua
require('neodev').setup({})
```

### Expected Behavior

I should be able to get `neodev` type information in the `after` folder.

### Repro

```Lua
-- I just left the below, so I can edit in it if necessary.
-- If you can't reproduce the problem, I will write a proper
-- repro.lua file.

-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/neodev.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by wookayin** [comment]
I can't tell why this really happens, but I believe this has something to do with #158. What I found so far is neodev or lua_ls behaves differently in workspace configuration depending on which directory the language server was launched. In some dirs libraries are loaded well, in other dirs no luck.

**Comment by Danielkonge** [comment]
> I can't tell why this really happens, but I believe this has something to do with #158. What I found so far is neodev or lua_ls behaves differently in workspace configuration depending on which directory the language server was launched. In some dirs libraries are loaded well, in other dirs no luck.

With commit 3941036e3da9b0dc09244036d20c590b6d752175 everything works as expected, so I am pretty sure that the change in https://github.com/folke/neodev.nvim/commit/c6be05aab078827e51aabdc64cc9fba7c06d27b7 causes problems. I haven't really looked into this though, so I am not sure what the exact problem is. 

For now I am just using that commit and everything works fine (both in my `after` directory and my local plugin directories).

If you think this is the same issue as in #158, do you think I should just close this as a duplicate?

**Comment by wookayin** [comment]
Hmm if it's about c6be05a, maybe it is not related to #158. But I'm not quite sure as I lack understanding what's going on here --- @folke can give us a better insight.

**Comment by Danielkonge** [comment]
Adding a `.luarc.json` in `~/.config/nvim` with
```json
{
    "$schema": "https://raw.githubusercontent.com/sumneko/vscode-lua/master/setting/schema.json",
    "runtime.version": "LuaJIT"
}
```
fixed my issue with newer commits. 

I will leave the issue open for now, in case anyone else runs into this problem, but the problem is solved for me now (feel free to close it).
