### ISSUE TITLE
bug: neodev not working with mason-lspconfig

### ISSUE THREAD

**Issue by ej-shafran** [folke/neodev.nvim#180]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

macOS 14

### Describe the bug

I cannot seem to get `neodev` working in my config directory, even with a super minimal config that installs `lua_ls` with `mason-lspconfig`... I get `Undefined global "vim"` warnings whenever I try to use the `vim` object...

### Steps To Reproduce

1. Copy the repro below into `~/.config/nvim/repro.lua`
2. Run `nvim -u ~/.config/nvim/repro.lua ~/.config/nvim/repro.lua`
3. Wait for Lazy to finish installing the plugins
4. Wait for Mason to finish installing `lua-language-server` (use `:Mason` to see the progress)
5. Close Neovim
6. Do step 5 again
7. Enter insert mode
8. Exit insert mode
9. See warnings...

### Expected Behavior

This simple config to work with Neodev.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/neodev.nvim",
  "neovim/nvim-lspconfig",
  "williamboman/mason-lspconfig.nvim",
  "williamboman/mason.nvim",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

require("mason").setup()
require("mason-lspconfig").setup {
  ensure_installed = { "lua_ls" }
}
require("neodev").setup()
require("lspconfig").lua_ls.setup {}
```

**Comment by refarb** [comment]
I also recently (aka up until just now) had the same/a similar problem.
In my case the lua language server incorrectly set the project root to / which obviously disables neodev as that is not a neovim config directory.
Creating a barebones `.luarc.json` with only the schema (from the lua language server docs) and lua runtime version set to `LuaJIT` seems to have fixed my problem.

**Comment by xzbdmw** [comment]
> I also recently (aka up until just now) had the same/a similar problem. In my case the lua language server incorrectly set the project root to / which obviously disables neodev as that is not a neovim config directory. Creating a barebones `.luarc.json` with only the schema (from the lua language server docs) and lua runtime version set to `LuaJIT` seems to have fixed my problem.

Could you share how to set `Luajit`:)

**Comment by refarb** [comment]
Sure! All I put into the `.luarc.json` file sitting next to my `init.lua` was this:
```json
{
    "$schema": "https://raw.githubusercontent.com/sumneko/vscode-lua/master/setting/schema.json",
    "runtime.version": "LuaJIT"
}
```

The `"$schema"` came from the official lua language server documentation regarding the [config files](https://github.com/LuaLS/lua-language-server/wiki/Configuration-File#json-schema) and the `runtime.version` key came from the same page while the value was my best guess at how the server likely stored/referred to the LuaJIT runtime.

**Comment by natemaia** [comment]
I've had the same issue recently and the above `.luarc.json` worked perfectly.

**Comment by Rimann91** [comment]
I have this exact issue, however the .luarc.json doesnt seem to be making a difference

**Comment by daniele821** [comment]
for me neodev works only if i specify it as a dependency for lspconfig, mason, and mason-lsp

``` lua
	"neovim/nvim-lspconfig",
	dependencies = {
		"williamboman/mason.nvim",
		"williamboman/mason-lspconfig.nvim",
		{ "folke/neodev.nvim", opts = {} },
	},
```

if i do anything else, for some reason neodev does not work.

If you want, give it a try

**Comment by dg1234uk** [comment]
It started working for me after I put `neodev.nvim` as a dependency of `nvim-lspconfig` and then also trigged `nvim-lspconfig` on `LspAttach`. However, I subsequently installed the `luacheck` linter with Mason and using with `nvim-lint` which brought the `accessing undefined variable 'vim'` back.
