### ISSUE TITLE
feature: plugin description on hover

### ISSUE THREAD

**Issue by laurigates** [folke/neodev.nvim#184]
### Did you check the docs?

- [X] I have read all the neodev.nvim docs

### Is your feature request related to a problem? Please describe.

I don't always remember the function of each plugin I have installed and often have to check externally on GitHub for example.

### Describe the solution you'd like

Hovering on plugin names in my configuration could display the description of the plugin. Like the description plugins have in their GitHub about-section.

The ability to open the repo GitHub page like hovering does in lazy.nvim would be nice too.

### Describe alternatives you've considered

Being able to jump to definition from the plugin names. But maybe that's another feature request since it's a bit different.

**Comment by bwpge** [comment]
This doesn't solve your ask for plugin descriptions on hover, but [`gx.nvim`](https://github.com/chrishrb/gx.nvim) can open plugin pages from repo shorthands like `foo/bar`.
