### ISSUE TITLE
bug: Opening another workspace breaks first workspace's resolved symbols

### ISSUE THREAD

**Issue by aarondill** [folke/neodev.nvim#190]
### Did you check docs and existing issues?

- [X] I have read all the neodev.nvim docs
- [X] I have searched the existing issues of neodev.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2281+g0e9a33572

### Operating system/version

Arch Linux

### Describe the bug

Opening a second file in a different workspace causes `vim` and lua builtins like `require` to become unrecognized in the first file.
This issue and #183 might be the same issue
Note: I've bisected the issue and it first appears in c6be05aab078827e51aabdc64cc9fba7c06d27b7

### Steps To Reproduce

1. Open `init.lua`
2. input `vim.keymap.set()` (or any other `vim.*` function)
3. note that vim is recognized as a gloabl
4. press `gd` to go to the definition of `vim.keymap.set`
5. `:bn` to return to the first file
6. Note that `vim` is no longer recognized as a global

### Expected Behavior

No diagnostics and proper functionality.
This worked before c6be05aab078827e51aabdc64cc9fba7c06d27b7.

### Repro
<details>
<summary>press to expand</summary>

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "folke/neodev.nvim", config = true },
  {
    "neovim/nvim-lspconfig",
    event = { "BufReadPre", "BufNewFile", "BufEnter" },
    dependencies = {
      "folke/neodev.nvim",
      "mason.nvim",
      "williamboman/mason-lspconfig.nvim",
    },
    config = function()
      ---@diagnostic disable-next-line: missing-fields
      require("lspconfig").lua_ls.setup({})
      vim.keymap.set("n", "gd", vim.lsp.buf.definition, {})
    end,
  },
  {
    opts = { ensure_installed = { "lua_ls" } },
    "williamboman/mason-lspconfig.nvim",
    dependencies = { "mason.nvim" },
  },
  {
    "williamboman/mason.nvim",
    cmd = "Mason",
    build = ":MasonUpdate",
    opts = {},
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

</details>

**Comment by rcartafz** [comment]
#183  is still broken after updating
