### ISSUE TITLE
The name change should probably be announced with a breaking change

### ISSUE THREAD

**Issue by melkster** [folke/neodev.nvim#74]
I just spent an hour debugging why I kept getting the error `module 'lua-dev' not found` and just now I realized that the name changed :)

**Comment by smjonas** [comment]
That's weird, it did not break for me. Maybe the following is not enough and it's safer to keep the `lua/lua-dev/init.lua` file? 
https://github.com/folke/neodev.nvim/blob/5d944b6172eebc6c56e6f6d03a50723f20ff3890/after/plugin/lua-dev.lua#L1-L3

**Comment by folke** [comment]
@melkster it shouldn't break as @smjonas menioned.

Did you require any files from lua-dev besides the top level `init.lua`? And what was your use-case for that?

**Comment by ivandzf** [comment]
> I just spent an hour debugging why I kept getting the error `module 'lua-dev' not found` and just now I realized that the name changed :)

lol, me too xD

**Comment by folke** [comment]
@ivandzf can you post the exact error you got? I want to make sure other users don't suffer the same problem.

The after plugin should have prevented any errors with the rename

**Comment by ivandzf** [comment]
my error is quite similar with  @melkster, the module is not found

```
Error detected while processing /Users/ivan/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/ivan/.config/nvim/lua/lsp/server/lua.lua:2: module 'lua-dev' not found:
        no field package.preload['lua-dev']
        no file './lua-dev.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-beta3/lua-dev.lua'
        no file '/usr/local/share/lua/5.1/lua-dev.lua'
        no file '/usr/local/share/lua/5.1/lua-dev/init.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/lua-dev.lua'
        no file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/lua-dev/init.lua'
        no file './lua-dev.so'
        no file '/usr/local/lib/lua/5.1/lua-dev.so'
        no file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/lua-dev.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /Users/ivan/.config/nvim/lua/lsp/server/lua.lua:2: in main chunk
        [C]: in function 'require'
        /Users/ivan/.config/nvim/lua/lsp/init.lua:101: in main chunk
        [C]: in function 'require'
        /Users/ivan/.config/nvim/init.lua:5: in main chunk
```

just change the require to `neodev` then it will work perfectly

**Comment by folke** [comment]
I just changed it to what @smjonas suggested. Looks like your after/plugin didn't get executed. Adding the lua file should now definitely work for everyone.
