### ISSUE TITLE
Neovim < 0.7.0?

### ISSUE THREAD

**Issue by ViViDboarder** [folke/neodev.nvim#75]
It looks like the Readme was updated to require this minimal version. Were breaking changes introduced breaking older versions? If so, could a tag be created so that I can pin those? v0.7.0 isn't yet on Debian Stable or Ubuntu LTS repos so I try to make sure my configs support those minimal versions at the very least.

**Comment by folke** [comment]
Feel free to pin any commit. For the latest version you need 0.7.0.

The latest version is miles ahead of any version that's older than a couple of months ago.

**Comment by ViViDboarder** [comment]
Yea, I would, but I’m not sure when comparability was broken. If you’re not sure of the commit, do you have an idea of when or what feature is now used causing the breaking change so I can search and try to narrow in on a commit?

**Comment by folke** [comment]
Nighter am I, sorry. You'll have to look for yourself. 0.7.0 is supported. Any version below that is not

**Comment by ViViDboarder** [comment]
No problem. Just thought I’d check. I’ll try to come up with a test harness and then use git bisect. I haven’t really had a good excuse to try that yet.
