### ISSUE TITLE
Guide for "You're using the old way of setting up neodev (previously lua-dev)"

### ISSUE THREAD

**Issue by wookayin** [folke/neodev.nvim#76]
My experience for migration from lua-dev to neodev.nvim (#74) is not very smooth. Although I changed `require "lua-dev"` to `require "neodev"`, I still get the warnings:

```
2022-10-15T15:26:09 neodev.nvim  WARN You're using the old way of setting up neodev (previously lua-dev).                                                    
Please check the docs at https://github.com/folke/neodev.nvim#-setup 
```

But the docs really do not tell clearly what has been changed and what is the expected, new way of configuring the plugin.

The README has

```
- IMPORTANT: make sure to setup neodev BEFORE lspconfig
require("neodev").setup({
  -- add any options here, or leave empty to use the default settings
})
```

and calling `require("neodev").setup` will set `settings.legacy = true`, in which case such a deprecation warning will appear. Can you please improve the docs or let me know how am I supposed to migrate?

**Comment by folke** [comment]
That warning is unrelated to the rename. The way of configuring neodev changed a couple of months ago. Only now we show a warning if you're using it the old way.

If you check how you use it and you check the neodev docs, it should be very clearly how to set it up?

You're passing the result of the setup call of `neodev` to lspconfig. You should **no longer** do that. As you can see in the readme, that;s not how you should do it.

So again, just follow the docs. Call Neodev setup and then setup the lua language server as any other lsp server.

**Comment by smjonas** [comment]
I actually also have a similar problem as @wookayin and am not sure what I'm doing wrong. Previously I used this code (the returned value gets passed to `require("lspconfig").setup`):
```lua
local neodev_setup = require("neodev").setup {}
return vim.tbl_deep_extend("force", neodev_setup, { settings = settings, on_attach = on_attach })
``` 
Then I changed it to this as described in the readme:
```lua
require("neodev").setup()
return { settings = settings, on_attach = on_attach }
```
With this new approach, `neodev` won't work because the settings passed to the LSP server are not "patched". What am I missing?

**Comment by folke** [comment]
They don't need to be patched. there. That is done automatically through lsp-config.

Now, we only configure your lua project for nvim, when it effectively is a Neovim config directory, or looks like a Neovim plugin directory.

@smjonas If you say it doesn't work, what is your lsp root dir? `:LspInfo`

**Comment by smjonas** [comment]
Got it, that makes sense. My root dir is `/home/user/.config/nvim/lua` for `sumneko_lua` (`null-ls` is also active at `/home/user` if that's relevant)

**Comment by folke** [comment]
@smjonas your root directory is wrong. You probably have one of the root files in that directory https://github.com/neovim/nvim-lspconfig/blob/35a731bddaf20be0a2a0492cfa489ae6130a4eb6/lua/lspconfig/server_configurations/sumneko_lua.lua#L3

Those root files should be in the nvim directory. That's your root.

Eitehr way, I can see to make it work like this, but you'll likely have other issues with sumneko if your root dir is wrong.

**Comment by smjonas** [comment]
Thanks a lot! The issue was that I had a `.stylua.toml` file in the `nvim/lua` directory instead of in `nvim`.

**Comment by folke** [comment]
@smjonas I just pushed a fix so that neodev also works for wrongly configured lua projects, but again, that will definitely lead to other issues.

Glad you were able to solve it with moving the .stylua.toml

**Comment by wookayin** [comment]
> Call Neodev setup and then setup the lua language server as any other lsp server.

Thanks a lot @folke for your kind explanation and comparison between the old (deprecated) and the new (recommended) way of configuration. I was also lost a while ago about how config for sumneko-lua would work under the hood, but the configs now work well for me after following the suggestion.
