### ISSUE TITLE
Warning using an alias for vim.opt (and probably others)

### ISSUE THREAD

**Issue by BeTmAsTeR** [folke/neodev.nvim#77]
I'm experiencing this strange behavior, if i alias vim.opt to something shorter like "o" and use it to set some options, sumneko-lua with neodev spits out a lot of warnings about the types i'm using, if i use vim.opt directly those error disappear

![image](https://user-images.githubusercontent.com/761740/196051616-e76cd535-65e1-41c5-85b4-5efaafcff20f.png)

![image](https://user-images.githubusercontent.com/761740/196051652-cfc24717-4391-4281-898e-a8d28bce06c1.png)

**Comment by folke** [comment]
That's not really possible to fix.

`vim.opt.foldmethod` for example is not a string. Its an option object.

You can still set it to a string, but that's because of special meta tables on the `vim.opt` object.

What I mean, is that it's not possible to 100% accurately model this with types.

I'll close this, since this is a limitation of the way vim.opt works and typing.

**Comment by ColdSpirit0** [comment]
@BeTmAsTeR you can add option in diagnostics to ignore it:
```lua
lspconfig.sumneko_lua.setup({
   settings = {
      Lua = {
         diagnostics = {
            disable = {
               "assign-type-mismatch",
               "unused"
            }
         },
      },
   },
})
```

@folke it will be helpful if you add it to readme

**Comment by folke** [comment]
@ColdSpirit0 I would highly advise against doing that, since that will disable those diagnostics in your workspace, which is not what you want. You can ignore the lines in your code using the code actions.

**Comment by ColdSpirit0** [comment]
@folke thanks! It will help too, but I dont think I need strict type checking in my config files: too much to disable in every file.

**Comment by cxwx** [comment]
@ColdSpirit0 Can I disable `assign-type-mismatch` only for `vim.opt.something`?

**Comment by ColdSpirit0** [comment]
@cxwx I don't know, sorry. I think it is not possible. You can check the wiki here for server configuration: https://github.com/LuaLS/lua-language-server

I've commented out the lines above in my config and haven't seen any warnings for now. It's possible this problem has been fixed.
