### ISSUE TITLE
Restoring session with this plugin causes the first buffer to be all white

### ISSUE THREAD

**Issue by amaanq** [folke/neodev.nvim#78]
As per the title, when I restore my session with your 'persistence' plugin, the first buffer has no treesitter highlighting and text is all white. Running :e works to refresh and get highlighting back, but I'd say this is a bug with neodev as it doesn't occur when disabled/uninstalled.

on second thought it might not be neodev, I'm getting this issue what seems to be at random, and disabling a plugin might work once, but then re-enabling it will have it still work or disabling it will have the issue again. My config is heavily based on yours, I wonder, do you get this issue too? It's a bit annoying :slightly_smiling_face: would love a solution to this!

Edit: I've all but given up. 5+ plugins (in your dotfiles) cause this issue. And it's erratic too, so I'm giving up and will rely on :e to do the job. Sorry!

**Comment by folke** [comment]
Hi! I don't have this issue, but had this in the past. Likely due to lazy-loading treesitter. Best not to lazy-load it. It should fix your issue

**Comment by amaanq** [comment]
My config is heavily based off yours (like 90%+ the same, just a couple keybind tweaks/added plugins on my end), and I don't believe you're lazy loading treesitter :sweat_smile: oh well

**Comment by amaanq** [comment]
ok, I've found the cause, I modified my null-ls config to load rust-tools when detected, going to open issue in your dot repo
