### ISSUE TITLE
performance: Neovim UI blocks when loading lua LSP via neodev

### ISSUE THREAD

**Issue by wookayin** [folke/neodev.nvim#80]
I realized that very recently (probably after switching to neodev.nvim before lua-dev.nvim) the neovim UI blocks as soon as I open a lua file and the LSP server starts. Please see the GIF below:

![neodev performance issue](https://user-images.githubusercontent.com/1009873/197111454-48a975ee-3db6-4d79-a500-8178b6fe416d.gif)

You can feel the UI freezing because neovim's main thread blocks: nvim-notify will not render while neovim UI is blocking. This happens as soon as `lspconfig.sumneko_lua.setup { ... }` is called, where we have configured sumneko_lua via neodev. This issue, however, does not happen when we do not have a `neodev.setup {}` call.

I'm not sure this is a recent regression or such a bug happened since quite a long time ago, or this is a bug of neovim or the sumneko language server itself rather than neodev.vim -- but I don't think I was feeling this until very recently.

I have *a lot of* vim (lua) plugins so I assume scanning the large filesystem would be a probable reason of blocking. Any ideas? Thank you!

My environments:

- neovim 0.9.0-nightly (but happens too in neovim 0.7.0 and neovim 0.8.0)
- neodev.nvim version: bbc313f
- Happens both in macOS and Linux amd64 (everywhere)

<details>
<summary>My config (excerpt)</summary>

```
  require("neodev").setup {
    settings = {
      Lua = {
        runtime = {
          version = 'LuaJIT',   -- Lua 5.1/LuaJIT
        },
        completion = { callSnippet = "Disable" },
        workspace = { maxPreload = 8000 },
      },
    },
  }

...

  -- or via lspinstaller callback
  lspconfig.sumneko_lua.setup { }

```

</details>

**Comment by folke** [comment]
I can't reproduce this, but just pushed a change, where the settings are no longer calculated on `setup`. This was no longer needed for a while, but was still there for backward compatibility.

As for your config, why do you pass `settings`? That's not mentioned anywhere in the docs and won't do anything at all. You need to pass that to the lspconfig setup call as you would do for any language server.

**Comment by wookayin** [comment]
The config was just a legacy from the previous config which I unawarely didn't remove. Those are supposed to be arguments to `lspconfig.sumneko_lua.setup {...}`--  Thanks for pointing this out, I will fix that.  But it has nothing to do with this performance issue, just a single `require("neodev").setup {}` call will still make the UI block.

With the latest 82423f5 commit (and the valid way of config) I still have the issue. I might dig more into sumneko_lua and try a bit more profiling to find out which exact line is the blocker, but I feel this might be a bug of something else than `neodev.nvim`.

**Comment by wookayin** [comment]
Probably this line introduced in 563e365b96ea5848e950e216929c08c69d3f4dda is the culprit:

```
function M.on_new_config(config, root_dir):
...
  local lua_dirs = vim.fn.glob(root_dir .. "/**/lua", false, true)
...
end
```

is the blocker: `vim.fn.()` is a synchronous API that would block the UI for a while (0.5 sec in my environments). Using some other APIs like `vim.loop.fs_scandir` would, I suppose, be fine.

**Comment by wookayin** [comment]
Or we can disable scanning `lua_dirs` unless `experimental.pathStrict` is set, because this seems to be the only place `lua_dirs` is being used.

**Comment by folke** [comment]
It's also used to detect plugin directories (with wrong root dirs).

I changed the implementation to check the lua dirs of the loaded buffers instead. This is more than enough and prevents the glob.

**Comment by wookayin** [comment]
Great! Can confirm now it's fast and neovim doesn't block. Thanks!

p.s. Would you mind removing the invalid label then?

**Comment by folke** [comment]
Done and glad it's solved!
