### ISSUE TITLE
Plugins doesn't load into workspace

### ISSUE THREAD

**Issue by anuvyklack** [folke/neodev.nvim#81]
I setup neodev the next way:

```lua
use { 'folke/neodev.nvim', as = 'neodev',
   config = function()
      require("neodev").setup{}
   end
}
use { 'neovim/nvim-lspconfig', as = 'lspconfig' }
```

And hover descriptions and completion for `vim` and `api` tables are working.

But I am a plugin developer, and my plugins are symlinked via packer into
runtime path like this:

```lua
use { '~/code/neovim-plugins/windows.nvim',
   requires = '~/code/neovim-plugins/animation.nvim',
   ...
}
```

And when I open any file inside `windows.nvim` directory, language server knows
nothing about other installed plugins and all references to `animation.nvim`
become warnings and go to definition also doesn't work.

When this plugin was `lua-dev` everything works fine.

**Comment by folke** [comment]
That is by design. Please check the section on `override`.

We enable the Neovim types for Neovim config directories and plugin directories.

Other plugins are only enabled for the Neovim config. 

Using the overrride, you can specify a list of plugins to enable per plugin project.
