### ISSUE TITLE
Feature request: allow setting up neodev without lspconfig

### ISSUE THREAD

**Issue by marcelbeumer** [folke/neodev.nvim#83]
Hi @folke, thanks for all your work on neodev.

I see you removed the "legacy setup", but I'm using my own code around `vim.lsp.start` instead of lspconfig. Could you provide a way to use neodev without lspconfig? I was quite happy with just getting a big sumneko settings table out of neodev!

See https://github.com/marcelbeumer/nvim-config/blob/29b0fd03e8a0ef3a97480a0bb70c00caf7c88ab6/lua/conf/lsp/server/lua_language_server.lua#L9

Thanks in advance!

Edit: it does work for me using lspconfig for neodev/sumneko and using nvim lsp API's directly for other lang servers, so it's really a feature request. https://github.com/marcelbeumer/nvim-config/blob/0fac69b0c5653af99adae8978135e4a40c3754fa/lua/conf/lsp/server/lua_language_server.lua

**Comment by folke** [comment]
Just pushed an update where you can use the `before_init` hook to configure Neodev. See the example in the README

**Comment by marcelbeumer** [comment]
works, thanks a lot!
