### ISSUE TITLE
Support for coc.nvim

### ISSUE THREAD

**Issue by alannotnerd** [folke/neodev.nvim#89]
It's great! I wonder if you have plan to support coc users?

**Comment by chrisgrieser** [comment]
[You can already do so with coc-sumneko-lua.](https://github.com/xiyaowong/coc-sumneko-lua/blob/main/settings.md#sumneko-luaenablenvimluadev)

**Comment by folke** [comment]
coc-sumneko seems to contain an old copy of this repo, which is not ideal I guess.

I don't use coc myself, and won't add support, however, it should be fairly easy to get the correct settings with the `require("neodev.sumneko").setup` method. Check the code to see how to use
