### ISSUE TITLE
return parameter of log levels is no integer when assign globally

### ISSUE THREAD

**Issue by chrisgrieser** [folke/neodev.nvim#91]
<img width="1566" alt="Pasted image 2022-11-28 16 34 25" src="https://user-images.githubusercontent.com/73286100/204318322-7711c8d8-9926-4999-92a6-7dad7b892d50.png">

<img width="1268" alt="Pasted image 2022-11-28 16 36 56" src="https://user-images.githubusercontent.com/73286100/204318421-ec6650e3-6476-4568-9ced-3a6c2c8730c4.png">

**Comment by folke** [comment]
First of all, you should not assign it globally?
er
Second, it seems you assigned it to a function ssomewhere else in your code.

Either way, this is not a neodev issue. That's just the lua-language-server

**Comment by chrisgrieser** [comment]
ah, I see, it's actually a global function from the lua lsp

<img width="508" alt="Pasted image 2022-11-28 16 45 36" src="https://user-images.githubusercontent.com/73286100/204320619-7db6d0ab-c502-4070-a0ce-f4400abd763e.png">

--- 

> First of all, you should not assign it globally?

any reason why this would be bad? I want to keep it as a shorthand in my `utils.lua`, like `g = vim.g` (only posted them in one file for demonstration purposes)

**Comment by folke** [comment]
globals are always bad practice. I personally would not do this as it can lead to collisions. As you just showed...
