### ISSUE TITLE
Cannot assign boolean to vim.opt_local.linebreak warning

### ISSUE THREAD

**Issue by HawkinsT** [folke/neodev.nvim#92]
In my init.lua I have:
```lua
vim.api.nvim_create_autocmd({ "FileType" }, {
    pattern = { "tex", "bibtex" },
    callback = function()
        vim.opt_local.linebreak = true
    end,
})
```
where I get the LSP warning "Cannot assign 'boolean' to 'vim.opt.linebreak'" on the fourth line (note: the warning doesn't say vim.opt_local.linebreak), despite linebreak requiring a boolean value (and the command working fine).

If I change this line to `vim.opt.linebreak = true` the warning goes away, or if I also add this line outside of the autocmd like so:
```lua
vim.opt_local.linebreak = true
vim.api.nvim_create_autocmd({ "FileType" }, {
    pattern = { "tex", "bibtex" },
    callback = function()
        vim.opt_local.linebreak = true
    end,
})
```
the warning also disappears. This doesn't appear to be an issue with other boolean settings (e.g. I tested with `vim.opt_local.termguicolors = true` and didn't receive the same warning).

I hope I'm reporting this to the right place, but please let me know if you believe the issue to be upstream and I'll report accordingly.

**Comment by musjj** [comment]
Some other issues related to `vim.{opt,opt_local,opt_global}`:
```lua
vim.opt.showmode = false -- no error
```
```lua
local opt = vim.opt
opt.showmode = false -- error
```

**Comment by Susensio** [comment]
I'm getting a similar error with the following code:
```lua
print(vim.opt_local.spell:get())
```
```
Cannot assign `vim.opt.spell|true` to parameter `vim.opt.spell`. - `true` cannot match `vim.opt.spell` - Type `true` cannot match `vim.opt.spell` - Type `boolean` cannot match `vim.opt.spell`
```
