### ISSUE TITLE
vim.loop.spawn missing second return value

### ISSUE THREAD

**Issue by beardedsakimonkey** [folke/neodev.nvim#93]
Hi, thanks for this plugin!

It seems the second return value for `vim.loop.spawn` is not properly annotated:
https://github.com/folke/neodev.nvim/blob/2d5a374b2c0d6d3521a2c49541c9c195b0646be6/types/stable/luv.lua#L2543

It should be `integer`.

Thanks in advance

**Comment by wookayin** [comment]
No, `integer|string` is correct it can return an error message.
